[build]
  base = "frontend/"
  command = "npm install && CI='' npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://exam-prep-backend.render.com/api"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 