services:
  - type: web
    name: exam-prep-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend 
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://shubhamrsaroj229:sinpluscos12@atlascluster.1rzraz5.mongodb.net/smartiq?retryWrites=true&w=majority&appName=AtlasCluster
      - key: JWT_SECRET
        value: zX8%kP4#uL2!mN6^bR3@wS5*hF1$tK9&jQ7vD5~nB6
      - key: EMAIL_USER
        value: shubhamrsaroj229@gmail.com
      - key: EMAIL_PASS
        value: efclfylixqlzaftc
      - key: FRONTEND_URL
        value: https://smartiqq.netlify.app
